version: '2'
services:
  frontend-base:
    image: victorjsv/frontend-base:latest
    build:
      context: ./frontend-base/
  micro-css:
    image: victorjsv/micro-css:latest
    build:
      context: ./micro-css/
  micro-html:
    image: victorjsv/micro-html:latest
    build:
      context: ./micro-html/
  micro-js:
    image: victorjsv/micro-js:latest
    build:
      context: ./micro-js/
  micro-sprites:
    image: victorjsv/micro-sprites:latest
    build:
      context: ./micro-sprites/
